name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          cmake_args: -D<USE_SSH>=OFF

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/*.tar.gz
          name: build_artifact.tar.gz

      - name: print file structure\
        run: dir /s /b /o:gn


  build-old:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B build -DUSE_SSH=OFF

    - name: Build
      run: cmake --build build
