name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Build
#        uses: nicledomaS/cmake_build_action@v1.4
#        with:
#          submodule_update: ON
#          cmake_args: -DUSE_SSH=OFF

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: old-build-conf
        run: cmake -B build -DUSE_SSH=OFF

      - name: old-build-build
        run: cmake --build build

      - name: print file structure\
        run: tree /f
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          path: build/*.tar.gz
#          name: build_artifact.tar.gz