name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-old:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: old-build-conf
        run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SSH=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -B build/release

      - name: print build structure
        run: tree /f

      - name: old-build-build
        run: cmake --build build/release --target create_clib_plugin -j 22

      - name: print file structure
        run: tree /f