name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup Ninja
#        uses: ashutoshvarma/setup-ninja@master
#        with:
#          # ninja version to download. Default: 1.10.0
#          version: 1.10.0

#      - name: Build with CMake
#        uses: ashutoshvarma/action-cmake-build@master
#        with:
#          build-dir: build
#          cc: MSVC
#          cxx: MSVC
#          configure-options: -G Ninja -DUSE_SSH=OFF
#          build-type: Release

#      - name: Build
#        uses: nicledomaS/cmake_build_action@v1.4
#        with:
#          submodule_update: ON
#          cmake_args: -G Ninja;-DUSE_SSH=OFF

#      - name: print file structure
#        run: tree /f
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          path: build/*.tar.gz
#          name: build_artifact.tar.gz
  build-old:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: old-build-conf
        run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SSH=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DCMAKE_MAKE_PROGRAM=${GITHUB_WORKSPACE}/ninja-build/ninja.exe -G Ninja -B build/release

      - name: print build structure
        run: tree /f

      - name: old-build-build
        run: cmake --build build/release --target create_clib_plugin -j 22

      - name: print file structure
        run: tree /f